### ISSUE TITLE
V3 :- cannot unmarshal string into Go struct field OrderEntity.cf_order_id of type int64

### ISSUE THREAD

**Issue by rinkujat25** [cashfree/cashfree-pg#57]
Hello Support,
I'm using cashfree package for go lan. and i'm facing issue while creating order 

<img width="957" alt="image" src="https://github.com/cashfree/cashfree-pg/assets/31273697/1ff690b8-e174-4d8c-a98e-c2a6c773ab82">
<img width="850" alt="image" src="https://github.com/cashfree/cashfree-pg/assets/31273697/5ade364e-1825-4151-bda3-af508e46e218">

**Comment by rinkujat25** [comment]
Hello support,
there is serval error's
<img width="956" alt="image" src="https://github.com/cashfree/cashfree-pg/assets/31273697/9d941f99-3e76-4dd1-8266-f32851ec2ebc">

**Comment by rinkujat25** [comment]
> Hi please use v4 version If your xApiVersion is 2023-08-01, you will have to use v4

please check above response

**Comment by suhas-cashfree** [comment]
Hi @rinkujat25 as mentioned in the other ticket, Please update to latest version of v3.
Create a new ticket, if the issue still persists.
