### ISSUE TITLE
\model_offer_type.go:16:2: "strings" imported and not used

### ISSUE THREAD

**Issue by rinkujat25** [cashfree/cashfree-pg#58]
Hello Support 
there is an error after install v3 package 
i'm facing this error after just installed package
<img width="959" alt="image" src="https://github.com/cashfree/cashfree-pg/assets/31273697/da897932-47b9-487d-af78-a14fd2e0bc31">

**Comment by suhas-cashfree** [comment]
Hi @rinkujat25 , this is fixed in the latest versions. Please update the package.
Closing this ticket for now, please create a new ticket, if the issue still persists.
